<template>
    <div>
        <div class="container about-content" data-bs-theme="dark"> 
            <p>
                This is a Chrome Extension that provides a set of tools for developers.
            </p>

            <div class="alert alert-warning" role="alert">
                The data generated by the plugin is fictitious and should be used solely for software testing and validation purposes.
            </div>           

            <table>
                <tr>
                    <td style="border: 0; border-bottom: 1px solid #ccc; margin-bottom: 16px;">
                        <img src="images/fernando.jpg" class="card-img-top" style="border-radius: 100%; width: 80px;" alt="Fernando França">
                    </td>
                    <td style="border: 0; border-bottom: 1px solid #ccc; margin-bottom: 16px;">
                        <h5 class="card-title">Fernando França</h5>
                        <p class="card-text">Software Engineer <br>
                            <small class="text-body-secondary">
                                <svg xmlns="http://www.w3.org/2000/svg" style="width: 14px; margin-right: 8px; fill: #fff"  viewBox="0 0 512 512"><!--! Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) Copyright 2023 Fonticons, Inc. --><path d="M64 112c-8.8 0-16 7.2-16 16v22.1L220.5 291.7c20.7 17 50.4 17 71.1 0L464 150.1V128c0-8.8-7.2-16-16-16H64zM48 212.2V384c0 8.8 7.2 16 16 16H448c8.8 0 16-7.2 16-16V212.2L322 328.8c-38.4 31.5-93.7 31.5-132 0L48 212.2zM0 128C0 92.7 28.7 64 64 64H448c35.3 0 64 28.7 64 64V384c0 35.3-28.7 64-64 64H64c-35.3 0-64-28.7-64-64V128z"/></svg>
                                <a href="mailto:fertioga@gmail.com">fertioga@gmail.com</a>
                            </small> 
                            <br>
                            <small class="text-body-secondary">
                                <svg xmlns="http://www.w3.org/2000/svg" style="width: 14px; margin-right: 8px; fill: #fff" viewBox="0 0 448 512"><!--! Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) Copyright 2023 Fonticons, Inc. --><path d="M100.28 448H7.4V148.9h92.88zM53.79 108.1C24.09 108.1 0 83.5 0 53.8a53.79 53.79 0 0 1 107.58 0c0 29.7-24.1 54.3-53.79 54.3zM447.9 448h-92.68V302.4c0-34.7-.7-79.2-48.29-79.2-48.29 0-55.69 37.7-55.69 76.7V448h-92.78V148.9h89.08v40.8h1.3c12.4-23.5 42.69-48.3 87.88-48.3 94 0 111.28 61.9 111.28 142.3V448z"/></svg>
                                <a href="https://www.linkedin.com/in/fernando-franca/" target="_blank">@fernando-franca</a>
                            </small>
                        </p>       
                    </td>
                </tr>
                <tr>
                    <td style="border: 0;">
                        <img src="images/karla.jpg" style="border-radius: 100%; width: 80px;" alt="Karla França">
                    </td>
                    <td style="border: 0;">
                        <h5 class="card-title">Karla França</h5>
                        <p class="card-text">UI/UX Designer <br>
                            <small class="text-body-secondary">
                                <svg xmlns="http://www.w3.org/2000/svg" style="width: 14px; margin-right: 8px; fill: #fff"  viewBox="0 0 512 512"><!--! Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) Copyright 2023 Fonticons, Inc. --><path d="M64 112c-8.8 0-16 7.2-16 16v22.1L220.5 291.7c20.7 17 50.4 17 71.1 0L464 150.1V128c0-8.8-7.2-16-16-16H64zM48 212.2V384c0 8.8 7.2 16 16 16H448c8.8 0 16-7.2 16-16V212.2L322 328.8c-38.4 31.5-93.7 31.5-132 0L48 212.2zM0 128C0 92.7 28.7 64 64 64H448c35.3 0 64 28.7 64 64V384c0 35.3-28.7 64-64 64H64c-35.3 0-64-28.7-64-64V128z"/></svg>
                                <a href="mailto:karlafrancamail@gmail.com">karlafrancamail@gmail.com</a>
                            </small> 
                            <br>
                            <small class="text-body-secondary">
                                <svg xmlns="http://www.w3.org/2000/svg" style="width: 14px; margin-right: 8px; fill: #fff" viewBox="0 0 448 512"><!--! Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) Copyright 2023 Fonticons, Inc. --><path d="M100.28 448H7.4V148.9h92.88zM53.79 108.1C24.09 108.1 0 83.5 0 53.8a53.79 53.79 0 0 1 107.58 0c0 29.7-24.1 54.3-53.79 54.3zM447.9 448h-92.68V302.4c0-34.7-.7-79.2-48.29-79.2-48.29 0-55.69 37.7-55.69 76.7V448h-92.78V148.9h89.08v40.8h1.3c12.4-23.5 42.69-48.3 87.88-48.3 94 0 111.28 61.9 111.28 142.3V448z"/></svg>
                                <a href="https://www.linkedin.com/in/karla-franca/" target="_blank">@karla-franca</a>
                            </small>
                        </p>
 
                    </td>
                </tr>
            </table>

            <h3 style="text-align: center; margin: 40px 0 24px 0;">If you enjoy using the plugin</h3>
            <div class="row">
                <div class="col" style="text-align: center;">
                    <p>
                        <a href="https://www.buymeacoffee.com/fertioga" target="_blank">
                            <img src="https://cdn.buymeacoffee.com/buttons/v2/default-yellow.png" alt="Buy Me A Coffee" style="height: 30px !important;width: 110px !important;" >
                        </a>
                    </p>
                    <p>
                        PIX: <br>
                        <img src="images/qr-code.png" alt="PIX">
                    </p>
                </div>
            </div>
            
            <p>
                © {{ year }} Data Ninja. All rights reserved. <br>
                version: {{ version }}
            </p>

        </div>

    </div>
</template>
<script>
export default {
    name: 'About',
    data() {
        return {
            year: '',
            version: '',
        };
    },
    mounted() {
        const now = new Date(); 
        this.year = now.getFullYear();

        this.version = chrome.runtime.getManifest().version;
    },
};
</script>
<style scoped>
    /* .about-content {
        margin-bottom: -700px;         
        padding: 24px;
    } */
</style>